apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: appargo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: b4ux1t3
        image: b4ux1t3/homer:latest
        ports:
        - containerPort: 8080